SASS-58 added other dividends page
hmrc/personal-income-tax-submission-frontend pull request #11
Opened 2020-10-23 14:42 UTC by juamalBlackman

2020-10-23 16:31 UTC, robert-webb-hmrc requested changes
Looks mostly good, hint text on page needs double checking.

2020-10-23 16:31 UTC, robert-webb-hmrc commented on app/views/dividends/OtherDividendsAmountView.scala.html
> +
There is some content missing from the jira screenshot (Please see grey hint text)
![Screenshot 2020-10-23 at 17 21 06](https://user-images.githubusercontent.com/28566263/97029029-c024b780-1554-11eb-8c5e-144f9868cbd4.png)

2020-10-26 08:36 UTC, juamalBlackman commented on app/views/dividends/OtherDividendsAmountView.scala.html
> +
missed this added

2020-10-26 09:55 UTC, robert-webb-hmrc approved these changes

2020-10-26 09:56 UTC, merged