Sass 570
hmrc/personal-income-tax-submission-frontend pull request #119
Opened 2021-04-01 13:58 UTC by AdamSmithHMRC

### Description
Created Model for Gift Aid on Personal Frontend with connector and parser, and added session value

https://jira.tools.tax.service.gov.uk/browse/SASS-513

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you addressed warnings where appropriate?

##### After PRs been Reviewed
- [ ]  Have you checked the PR Builder passes?
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked code coverage isn’t lower than previously?

2021-04-01 16:28 UTC, robert-webb-hmrc requested changes
Looks mostly good, can we address the following warn and the comment please?
<img width="1437" alt="Screenshot 2021-04-01 at 16 54 14" src="https://user-images.githubusercontent.com/28566263/113324922-99db2300-930f-11eb-801a-e07dff91ba88.png">

2021-04-01 16:46 UTC, robert-webb-hmrc approved these changes

2021-04-01 16:47 UTC, merged

2021-04-06 08:56 UTC, BenCosfordHMRC commented on app/models/giftAid/GiftAidPaymentsModel.scala
> +                                currentYear: Int,
missing `oneOffCurrentYear` field

2021-04-06 08:56 UTC, BenCosfordHMRC commented on app/models/giftAid/GiftAidPaymentsModel.scala
> +                                nonUkCharities: Int)
all ints should be big decimals

2021-04-06 08:56 UTC, BenCosfordHMRC commented on app/models/giftAid/GiftAidSubmissionModel.scala
> +                                  giftsModel: GiftsModel)
giftAidPaymentsModel should be giftAidPayments & giftsModel should be gifts so that we don't have to do any transformation/specific json reads in the backends

2021-04-06 08:56 UTC, BenCosfordHMRC commented on app/models/giftAid/GiftsModel.scala
> +                      investmentsNonUkCharities: Int)
all ints should be big decimals