Sass 573
hmrc/personal-income-tax-submission-frontend pull request #122
Opened 2021-04-07 13:54 UTC by matt712

### Description
No longer use radio button pattern for previously submitted.

[SASS-573](https://jira.tools.tax.service.gov.uk/browse/SASS-573)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [X]  Have you run the tests?
- [X]  Have you run the journey tests?
- [X]  Have you addressed warnings where appropriate?

##### After PRs been Reviewed
- [ ]  Have you checked the PR Builder passes?
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked code coverage isn’t lower than previously?

2021-04-08 09:18 UTC, joeyymoore commented on app/controllers/dividends/UkDividendsAmountController.scala
> +import forms.{UkDividendsAmountForm}
This gives a warning around removing the braces, may aswell remove them to get rid of the warning

2021-04-08 09:21 UTC, joeyymoore commented on app/views/dividends/UkDividendsAmountView.scala.html
> +    @heading(s"dividends.uk-dividends-amount.heading.${if(user.isAgent) "agent" else "individual"}", Some(messages("dividends.caption", (taxYear - 1).toString, taxYear.toString)), "govuk-!-margin-bot
you've made a @headingForUse variable above, you could probably call it here right instead of making the same string concept again?

2021-04-08 09:25 UTC, joeyymoore commented on test/controllers/interest/AccountsControllerSpec.scala
> +  def maxRequestWithInvalidForm(cyaModel: InterestCYAModel = interestCyaModel): FakeRequest[AnyContentAsFormUrlEncoded] = fakeRequest
Just to double check you meant to add this stuff as its interest related and not dividends? im guessing it was just missing in general?

2021-04-08 09:26 UTC, joeyymoore commented on test/views/dividends/UkDividendsAmountViewSpec.scala
> -  lazy val priorOrNewAmountForm: Form[PriorOrNewAmountModel] = PriorOrNewAmountForm.priorOrNewAmountForm(priorAmount)
You could do with removing the imports for the PriorOrNewAmountForm/PriorOrNewAmountModel  aswell as they are no longer used

2021-04-08 09:29 UTC, joeyymoore commented
if you look at Inas PR for https://github.com/hmrc/personal-income-tax-submission-frontend/pull/121/files. Could you add the checks in the viewSpec for the new text on the screen, i.e. the textOnPageCheck(tellUsTheValueIndividual,tellUsTheValueSelector) checks for when prior data is passed in.

2021-04-08 09:32 UTC, matt712 commented on test/controllers/interest/AccountsControllerSpec.scala
> +  def maxRequestWithInvalidForm(cyaModel: InterestCYAModel = interestCyaModel): FakeRequest[AnyContentAsFormUrlEncoded] = fakeRequest
I was just trying to bump test coverage a little

2021-04-08 09:50 UTC, joeyymoore commented on test/controllers/interest/AccountsControllerSpec.scala
> +  def maxRequestWithInvalidForm(cyaModel: InterestCYAModel = interestCyaModel): FakeRequest[AnyContentAsFormUrlEncoded] = fakeRequest
thats fine - just double checking you meant to make these changes

2021-04-09 10:18 UTC, joeyymoore commented
So i think theres still an issue in that when you keep changing the amount and coming back in, the value is empty every time (in the input field), whereas i think Ben said that this should only happen the first time.

2021-04-13 14:40 UTC, BenCosfordHMRC requested changes

2021-04-13 14:40 UTC, BenCosfordHMRC commented on app/controllers/dividends/DividendsCYAController.scala
> -          .addingToSession(SessionValues.DIVIDENDS_CYA -> Json.toJson(cyaModel).toString())
This line shouldn't be removed.

2021-04-13 14:40 UTC, BenCosfordHMRC commented on app/controllers/dividends/UkDividendsAmountController.scala
> +        if(previousAmount.isDefined) {
It should only fill if the prior amount is different from the CYA amount. 

Probably can copy from Ina's controller

if(previousAmount.contains(prior)) {

2021-04-13 14:40 UTC, BenCosfordHMRC commented on conf/messages
> +dividends.uk-dividends-amount.change-amount.caption.individual = Tell us the value of the dividends you got, in pounds. You can find this information in their dividend voucher.
I can't see 'their' in the content on the slides I think it should be 'You can find this information in your dividend voucher.'

2021-04-13 14:40 UTC, BenCosfordHMRC commented on conf/messages
> +dividends.uk-dividends-amount.change-amount.caption.agent = Tell us the value of the dividends your client got, in pounds. You can find this information in their dividend voucher.
Same as above, 'their' should be removed. Shoudl be 'You can find this information in your client’s dividend voucher.'

2021-04-13 14:40 UTC, BenCosfordHMRC commented on conf/messages.cy
> +dividends.uk-dividends-amount.change-amount.caption.agent = Tell us the value of the dividends your client got, in pounds. You can find this information in their dividend voucher.
As above, copy from english messages file.

2021-04-13 15:11 UTC, matt712 commented on app/controllers/dividends/DividendsCYAController.scala
> -          .addingToSession(SessionValues.DIVIDENDS_CYA -> Json.toJson(cyaModel).toString())
I needed to remove it to get some functionality

2021-04-13 15:26 UTC, matt712 commented on app/controllers/dividends/DividendsCYAController.scala
> -          .addingToSession(SessionValues.DIVIDENDS_CYA -> Json.toJson(cyaModel).toString())
Added that line back, it's not showing as outdated though

2021-04-13 15:49 UTC, BenCosfordHMRC approved these changes

2021-04-13 15:53 UTC, merged