Sass 575
hmrc/personal-income-tax-submission-frontend pull request #125
Opened 2021-04-12 09:18 UTC by michael-rob-poole

### Description
Remove radio buttons and add informational paragraph for user

Add a link to the relevant story in Jira
[SASS-575](https://jira.tools.tax.service.gov.uk/browse/SASS-575)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you addressed warnings where appropriate?

##### After PRs been Reviewed
- [ ]  Have you checked the PR Builder passes?
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked code coverage isn’t lower than previously?

2021-04-12 13:46 UTC, joeyymoore commented
Needs journey tests merging with this https://github.com/hmrc/income-tax-submission-journey-tests/pull/53

2021-04-12 15:42 UTC, ina-tu requested changes

2021-04-12 15:42 UTC, ina-tu commented on test/views/interest/ChangeAccountAmountViewSpec.scala
>    val captionSelector = ".govuk-caption-l"
inputSelector not used. Can be removed

2021-04-12 15:42 UTC, ina-tu commented on test/views/interest/ChangeAccountAmountViewSpec.scala
>    val h1Selector = "h1"
h1 selector is not used. Can be removed

2021-04-12 15:42 UTC, ina-tu commented on test/views/interest/ChangeAccountAmountViewSpec.scala
> +            welshToggleCheck("English")
language should be "Welsh"

2021-04-12 15:42 UTC, ina-tu commented on test/views/interest/ChangeAccountAmountViewSpec.scala
> +            )(user.copy(arn = Some("XARN1234567")), messages, mockAppConfig)
change messages file to `welshMessages`

2021-04-12 15:42 UTC, ina-tu commented on test/views/interest/ChangeAccountAmountViewSpec.scala
> +            )(user.copy(arn = Some("XARN1234567")), messages, mockAppConfig)
change messages to welshMessages

2021-04-12 15:42 UTC, ina-tu commented on test/views/interest/ChangeAccountAmountViewSpec.scala
> +            welshToggleCheck("English")
language should be "Welsh"

2021-04-12 16:07 UTC, michael-rob-poole commented on test/forms/ChangeAccountAmountFormSpec.scala
> +      emptyTest.errors should contain(FormError(amount, "changeAccountAmount.required.agent", List("taxed")))
Not sure - I just thought the test was that a form error would be generated if an error was found. Also, I thought those parameters were used to generate the error content in view so it would be tested there? Would I need one for individual as well?

2021-04-12 16:12 UTC, ina-tu commented on test/forms/ChangeAccountAmountFormSpec.scala
> +      emptyTest.errors should contain(FormError(amount, "changeAccountAmount.required.agent", List("taxed")))
Oh okay. It think it's fine how it is then

2021-04-13 16:36 UTC, BenCosfordHMRC approved these changes

2021-04-14 09:08 UTC, BenCosfordHMRC approved these changes

2021-04-14 09:12 UTC, ina-tu approved these changes

2021-04-14 09:48 UTC, merged