SASS-706 - Added logic to prevent users jumping around the dividend p…
hmrc/personal-income-tax-submission-frontend pull request #158
Opened 2021-05-10 10:36 UTC by Dula-J

…ages

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you addressed warnings where appropriate?

##### After PRs been Reviewed
- [ ]  Have you checked the PR Builder passes?
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked code coverage isn’t lower than previously?

2021-05-10 15:23 UTC, robert-webb-hmrc requested changes
Can we address the following warns and Coverage issues as well please?
![Screenshot 2021-05-10 at 15 52 47](https://user-images.githubusercontent.com/28566263/117683466-ff8eba80-b1ab-11eb-86ee-2f031993782b.png)
<img width="1659" alt="Screenshot 2021-05-10 at 14 37 58" src="https://user-images.githubusercontent.com/28566263/117683480-03bad800-b1ac-11eb-876a-49a07895b6ac.png">
<img width="1658" alt="Screenshot 2021-05-10 at 14 39 04" src="https://user-images.githubusercontent.com/28566263/117683510-0caba980-b1ac-11eb-905e-d984f2ab81b4.png">

2021-05-11 08:44 UTC, TheDeadlyPianist commented on app/controllers/predicates/QuestionHelper.scala
> +        QuestionsJourney[M].questions(cya, taxYear).find(_.expectedPage == currentPage)
@robert-webb-hmrc 
This is a generic type. They're usually single letters.
I agree with everything else.

2021-05-11 09:32 UTC, Dula-J commented on app/models/DividendsCheckYourAnswersModel.scala
> +    override def questions(m: DividendsCheckYourAnswersModel, taxYear: Int): Set[Question] = Set(
Changed to "model"

2021-05-11 09:32 UTC, Dula-J commented on app/controllers/predicates/QuestionHelper.scala
> +        QuestionsJourney[M].questions(cya, taxYear).find(_.expectedPage == currentPage)
Addressed warnings and unused imports. Not sure how to be more descriptive with that type parameter because it can be anything.

2021-05-11 09:32 UTC, Dula-J commented on test/models/question/QuestionTest.scala
> +      "return FALSE when dependency is defined and false and page is defined " in {
Removed the multiple "ands"

2021-05-11 09:32 UTC, Dula-J commented on test/controllers/predicates/QuestionHelperTest.scala
> +      "Redirect to the first page of the questions journey (receivedDividendsPage) when viewing dividendsAmountPage and cya data is not present" in {
Not sure what you mean by incorrect page names?

2021-05-11 09:33 UTC, Dula-J commented on it/controllers/dividends/UkDividendsAmountControllerISpec.scala
> +          heading.text() shouldBe "Check your income from dividends"
Good shout, I've added the ViewHelpers to this spec and the "otherukdividends" controller spec

2021-05-11 09:34 UTC, Dula-J commented
DO NOT MERGE

2021-05-13 17:00 UTC, robert-webb-hmrc submitted a review, later dismissed
Just one small thing to change. All else looks fine So It gets my approval once the change is made, but since I am off tomorrow, someone else will need to approve and merge this PR.

2021-05-14 12:22 UTC, Dula-J commented on test/controllers/dividends/UkDividendsAmountControllerSpec.scala
> +    "redirect to the receive dividends page" when {
no, good spot

2021-05-14 13:02 UTC, BenCosfordHMRC approved these changes

2021-05-14 13:03 UTC, merged