Sass 836
hmrc/personal-income-tax-submission-frontend pull request #197
Opened 2021-06-18 13:18 UTC by TheDeadlyPianist

### Description
The DIvidends and Interest journeys now use mongo to store data instead of the session.
Gift Aid CYA no longer puts data into session, and is primed to have the mongo integration added in when the navigation story is ran.

Add a link to the relevant story in Jira
[SASS-836](https://jira.tools.tax.service.gov.uk/browse/SASS-817)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?
- [ ]  Have you checked for merge conflicts or any changes in the current master that may affect
 the current pull request?

### Checklist PR Raiser
##### Before creating PR
- [x]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [x]  Have you addressed warnings where appropriate?
- [x]  Have you rebased against the current version of master? 

##### After PRs been Reviewed
- [ ]  Have you checked the PR Builder passes?
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked code coverage isn’t lower than previously?
- [ ]  Have you checked for merge conflicts or any changes in the current master that may affect
 the current pull request?

2021-06-21 08:57 UTC, robert-webb-hmrc commented
test this please

2021-06-21 17:38 UTC, robert-webb-hmrc requested changes
Can we also address these warns?

![Screenshot 2021-06-21 at 10 35 13](https://user-images.githubusercontent.com/28566263/122804248-95475a80-d2bf-11eb-9bb9-97cc65b6dae2.png)

2021-06-21 17:40 UTC, robert-webb-hmrc commented
Might be good if we could pop up some dependency versions as well
![Screenshot 2021-06-21 at 18 39 42](https://user-images.githubusercontent.com/28566263/122804703-20c0eb80-d2c0-11eb-91d7-d8103faaaddb.png)

2021-06-22 12:21 UTC, TheDeadlyPianist commented on it/utils/IntegrationTest.scala
> +  def emptyUserDataStub(): StubMapping = {
I use this one all the time.

2021-06-22 12:22 UTC, TheDeadlyPianist commented on it/controllers/dividends/OtherUkDividendsAmountControllerISpec.scala
> +          SessionValues.TAX_YEAR -> taxYear.toString
It's for the tax year predicate. I have no idea if not having it will make a difference, but I slapped it there for the sake of saving time, just in case.

2021-06-22 12:23 UTC, TheDeadlyPianist commented on it/repositories/UserDataRepositoryISpec.scala
> +  val dividendsUserData: DividendsUserDataModel = DividendsUserDataModel(
Doesn't make a difference.

2021-06-22 12:24 UTC, TheDeadlyPianist commented on app/controllers/predicates/AuthorisedAction.scala
> +          case _: AuthorisationException =>
Yes. They're not true wildcards. They have the type on them, so they will only catch that specific type.
Realistically, if you call the last option in a case match anything, without conditions, it is technically a wildcard. Since the "ex" wasn't being used, it behaves exactly the same as what I have here.

2021-06-22 13:48 UTC, robert-webb-hmrc commented
test this please

2021-06-22 14:26 UTC, robert-webb-hmrc commented
test this please

2021-06-22 14:47 UTC, BenCosfordHMRC commented on app/config/AppConfig.scala
> +  ).filterNot(_._2).map(_._1.stringify)
are these feature switches used anywhere?

2021-06-22 14:47 UTC, BenCosfordHMRC commented on app/common/SessionValues.scala
> +  val GIFT_AID_CYA = "GIFT_AID_CYA" //TODO To be removed
Is the plan to remove these in another PR?

2021-06-22 14:50 UTC, BenCosfordHMRC commented
This will need an update in app-config-base to add config for income-tax-submission

2021-06-22 14:54 UTC, TheDeadlyPianist commented on app/config/AppConfig.scala
> +  ).filterNot(_._2).map(_._1.stringify)
Turns out it isn't used. Something just above does a similar thing. Removed.

2021-06-22 14:55 UTC, TheDeadlyPianist commented on app/common/SessionValues.scala
> +  val GIFT_AID_CYA = "GIFT_AID_CYA" //TODO To be removed
CYA can be removed (done). Prior is still used in a lot of places. It will need removing after the navigation ticket is done.

2021-06-22 15:24 UTC, robert-webb-hmrc approved these changes

2021-06-22 15:25 UTC, merged