SASS-1180 Encryption
hmrc/personal-income-tax-submission-frontend pull request #238
Opened 2021-10-05 09:05 UTC by juamalBlackman

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-1180](https://jira.tools.tax.service.gov.uk/browse/SASS-1180)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of master?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current master that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of master?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2021-10-05 10:56 UTC, BenCosfordHMRC requested changes

2021-10-05 10:56 UTC, BenCosfordHMRC commented on app/repositories/UserDataRepository.scala
> +  var repoName: String = "UserDataRepository"
shouldn't use vars outside of tests. This could be `val repoName: String` which would be instantiated by the users of the UserDataRepository trait.

2021-10-05 10:56 UTC, BenCosfordHMRC commented on app/services/DividendsSessionService.scala
> +      encryptionService.encryptDividendsUserData(DividendsUserDataModel(
Any particular reason for having encrypting / decrypting here rather than in the repository? Introduces some duplication across the different income sources. 

Instead in the trait UserDataRepository you could have an encryption function & a decryption method defined.

Could be something like 

`val encryptionMethod: UnencryptedC => C`
`val decryptionMethod: C => UnencryptedC`

Then in say DividendsUserDataRepository you'd define encryptionMethod as encryptionService.encryptDividendsUserData & decryptionMethod as encryptionService.decryptDividendsUserData.

Then the encryption / decryption stuff could be as is like in employment FE / submission BE

2021-10-05 10:56 UTC, BenCosfordHMRC commented on app/services/DividendsSessionService.scala
> +            None
Since we've introduced the possibility of errors on getting data, we shouldn't return a None on an error case. Instead the error should be returned back up to the user i.e. errorHandler internal server error page. 

See https://github.com/hmrc/income-tax-employment-frontend/blob/master/app/services/EmploymentSessionService.scala#L77 for similar method

2021-10-05 10:56 UTC, BenCosfordHMRC commented on app/services/DividendsSessionService.scala
> +      case Left(_) => None
Same in this case a Left error is different than there being no data, should be presented with error page. If encryption would be moved to repo layer, would only have to cater for one left case in service also.

2021-10-05 10:56 UTC, BenCosfordHMRC commented on app/services/GiftAidSessionService.scala
> +      case Left(_) => None
as above Left error should be treated differently to no data

2021-10-05 10:56 UTC, BenCosfordHMRC commented on app/services/InterestSessionService.scala
> +      case Left(_) => None
as above

2021-10-05 10:56 UTC, BenCosfordHMRC commented on app/utils/PagerDutyHelper.scala
> +    val FAILED_TO_CREATE_DATA: PagerDutyKeys.Value = Value
the bottom 3 would need adding to alert config 
https://github.com/hmrc/alert-config/blob/master/src/main/scala/uk/gov/hmrc/alertconfig/configs/MtdItsass.scala

2021-10-05 10:57 UTC, BenCosfordHMRC commented on conf/application.conf
> +useEncryption = false
app config base PR would need raising to turn on in environments

2021-10-12 08:32 UTC, juamalBlackman commented on conf/application.conf
> +useEncryption = false
https://github.com/hmrc/app-config-base/pull/6274

2021-10-12 11:00 UTC, robert-webb-hmrc commented on app/services/InterestSessionService.scala
> +        None
As above, should this be a none?

2021-10-18 12:44 UTC, merged