Added frontend connector
hmrc/personal-income-tax-submission-frontend pull request #25
Opened 2020-11-19 12:53 UTC by matt712

2020-11-19 13:10 UTC, matt712 commented
Journey tests are failing

2020-11-23 16:49 UTC, robert-webb-hmrc requested changes

2020-11-23 16:49 UTC, robert-webb-hmrc commented on test/controllers/dividends/DividendsCYAControllerSpec.scala
> +          SessionValues.CLIENT_MTDITID -> Json.toJson("someMtdItd").toString(),
typo here

2020-11-23 16:49 UTC, robert-webb-hmrc commented on test/controllers/dividends/DividendsCYAControllerSpec.scala
> +          SessionValues.CLIENT_MTDITID -> Json.toJson("someMtdItd").toString(),
as above

2020-11-23 16:49 UTC, robert-webb-hmrc commented on test/services/DividendsSubmissionServiceSpec.scala
> +      val mtdItid = "SomeMtdItd"
typo here

2020-11-23 16:49 UTC, robert-webb-hmrc commented on app/services/DividendsSubmissionService.scala
> +/*
Could we review the coverage on the submission service? 
![Screenshot 2020-11-23 at 16 29 42](https://user-images.githubusercontent.com/28566263/99988193-3cefbf00-2da9-11eb-8416-7be9c53da75f.png)
![Screenshot 2020-11-23 at 16 29 50](https://user-images.githubusercontent.com/28566263/99988218-44af6380-2da9-11eb-9b70-b76c34e4f78e.png)

2020-11-23 16:49 UTC, robert-webb-hmrc commented on app/controllers/dividends/DividendsCYAController.scala
> +        case Right(DividendsResponseModel(NO_CONTENT)) => Redirect(appConfig.incomeTaxSubmissionOverviewUrl(taxYear)) //todo error handling
is this todo part of this ticket? would be better to remove it if not.

2020-11-23 17:32 UTC, robert-webb-hmrc requested changes

2020-11-23 17:32 UTC, robert-webb-hmrc commented on test/controllers/dividends/DividendsCYAControllerSpec.scala
> +          SessionValues.CLIENT_MTDITID -> Json.toJson("someMtdItd").toString(),
One typo left

2020-11-24 10:22 UTC, robert-webb-hmrc approved these changes

2020-11-24 10:22 UTC, merged