SASS-1088: Move some logic from controllers into service layer
hmrc/personal-income-tax-submission-frontend pull request #258
Opened 2022-01-17 15:29 UTC by jhkldev

### Description
Refactor logic from controllers into the service layer.

[SASS-1088](https://jira.tools.tax.service.gov.uk/browse/SASS-1088)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [X]  Have you run the tests?
- [X]  Have you run the journey tests? (where applicable)
- [X]  Have you addressed warnings where appropriate?
- [X]  Have you rebased against the current version of main?
- [X]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-01-17 16:17 UTC, robert-webb-hmrc commented
test this please

2022-02-01 09:48 UTC, robert-webb-hmrc requested changes
Please see comments - could we also cover the following if possible?
![Screenshot 2022-02-01 at 09 16 13](https://user-images.githubusercontent.com/28566263/151946470-2f38075a-da04-482b-b23d-a9107a76a226.png)
![Screenshot 2022-02-01 at 09 11 46](https://user-images.githubusercontent.com/28566263/151946476-6c1dee66-1b8a-4133-8023-89623514aff6.png)

2022-02-01 09:48 UTC, robert-webb-hmrc commented on app/models/interest/TaxedModel.scala
> +object TaxedModel {
I'm not sure this should be called TaxedModel if it's being used to map both types

2022-02-01 09:48 UTC, robert-webb-hmrc commented on test/models/interest/TaxedModelSpec.scala
> +class TaxedModelSpec extends UnitTest {
See above comment

2022-02-01 13:06 UTC, robert-webb-hmrc commented on test/models/interest/AccountAmountModelSpec.scala
> +    "return instance of TaxedModel containing name and tax amount if cya data, valid unique session id and tax type 'TAXED' is specified" in {
Could we change these test names to reflect the file name please?

2022-02-01 13:06 UTC, robert-webb-hmrc commented on test/models/interest/AccountAmountModelSpec.scala
> +      val taxedModel = AccountAmountModel.apply(cyaModel, "1", InterestTaxTypes.UNTAXED)
(and val names too)

2022-02-01 13:10 UTC, jhkldev commented on test/models/interest/AccountAmountModelSpec.scala
> +    "return instance of TaxedModel containing name and tax amount if cya data, valid unique session id and tax type 'TAXED' is specified" in {
Done 👍

2022-02-01 13:10 UTC, jhkldev commented on test/models/interest/AccountAmountModelSpec.scala
> +      val taxedModel = AccountAmountModel.apply(cyaModel, "1", InterestTaxTypes.UNTAXED)
Done 👍

2022-02-01 13:35 UTC, robert-webb-hmrc approved these changes

2022-02-01 13:36 UTC, merged