Sass 144
hmrc/personal-income-tax-submission-frontend pull request #26
Opened 2020-11-19 16:06 UTC by juamalBlackman

2020-11-19 18:05 UTC, robert-webb-hmrc requested changes

2020-11-19 18:05 UTC, robert-webb-hmrc commented on conf/application.conf
> +play.filters.headers.contentSecurityPolicy = "default-src 'self' 'unsafe-inline' localhost:9000 localhost:9032 www.google-analytics.com www.googletagmanager.com data:"
Currently the tracking.js script is blocked by the csp policy resulting in the following :
![Screenshot 2020-11-19 at 17 36 38](https://user-images.githubusercontent.com/28566263/99705286-6f3faa80-2a91-11eb-8046-861cc504359b.png)


To fix this issue we'll need to add tracking consent frontend into the csp (locally, this is localhost:12345). With this in mind it would also make sense to add tracking consent frontend to our service manager profile as well, so we can check our tags locally.

We'll also need to update our csp in app-config-staging to align with this.

Incidentally please note the other manual test you can do to verify these changes in the FAQ section : https://confluence.tools.tax.service.gov.uk/display/PLATUI/Integrating+with+tracking+consent+-+a+guide+for+service+teams

2020-11-20 11:11 UTC, juamalBlackman commented on conf/application.conf
> +play.filters.headers.contentSecurityPolicy = "default-src 'self' 'unsafe-inline' localhost:9000 localhost:9032 www.google-analytics.com www.googletagmanager.com data:"
added localhost:12345 and created pr for a service manager profile

2020-11-20 12:31 UTC, robert-webb-hmrc approved these changes

2020-11-20 12:38 UTC, merged