SASS-2863 Tailor interest gateway page
hmrc/personal-income-tax-submission-frontend pull request #275
Opened 2022-05-18 15:33 UTC by dnyuar

### Description
Creation of interest gateway page

Add a link to the relevant story in Jira
Parent ticket -> [SASS-11](https://jira.tools.tax.service.gov.uk/browse/SASS-11)

### Checklist PR Reviewer
##### Before Reviewing
- [x]  Have you pulled the branch down?
- [x]  Have you assigned yourself to the PR?
- [x]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [x]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [x]  Have you run the tests?
- [x]  Have you run the journey tests?
- [x]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [x]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [x]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [x]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [x]  Have you run the tests?
- [x]  Have you run the journey tests? (where applicable)
- [x]  Have you addressed warnings where appropriate?
- [x]  Have you rebased against the current version of main?
- [x]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-05-23 12:01 UTC, ina-tu commented on app/controllers/interest/InterestGatewayController.scala
> +        case Right(sessionData) =>
Is it worth extracting some of this into a service for the other gateway questions to use? I'm guessing the implementation for those questions will be similar to this

2022-05-23 12:05 UTC, ina-tu commented on app/views/interest/InterestGatewayView.scala.html
> +@import views.html.templates.helpers.InputRadio
you could use the InputRadioAlt helper instead to avoid introducing more accessibility issues

2022-05-23 13:28 UTC, ina-tu commented on app/controllers/interest/InterestGatewayController.scala
> +                Future.successful(Redirect(controllers.interest.routes.InterestCYAController.show(taxYear))) // redirect to zero warning error page
you can add TO DO in the comment so that it appears in IntelliJ's list of TO DOs

2022-05-23 13:45 UTC, ina-tu commented on it/controllers/interest/InterestGatewayControllerISpec.scala
> +
unused imports

2022-05-23 13:49 UTC, ina-tu commented on it/controllers/interest/InterestGatewayControllerISpec.scala
> +
you could move tests that don't check for any page content outside of the userScenrarios loop so it reduces the number of tests to run

2022-05-23 13:49 UTC, dnyuar commented on app/views/interest/InterestGatewayView.scala.html
> +@import views.html.templates.helpers.InputRadio
Updated

2022-05-23 13:53 UTC, ina-tu requested changes
needs a rebase

2022-05-23 13:58 UTC, ina-tu commented on app/controllers/interest/InterestGatewayController.scala
> +        case Left(_) => errorHandler.internalServerError()
missing coverage for the errorHandler.internalServerError() scenarios in the show and submit methods

2022-05-24 08:13 UTC, dnyuar commented on it/controllers/interest/InterestGatewayControllerISpec.scala
> +
Updated

2022-05-24 08:14 UTC, dnyuar commented on it/controllers/interest/InterestGatewayControllerISpec.scala
> +
Updated

2022-05-24 12:17 UTC, ina-tu approved these changes

2022-05-24 12:19 UTC, merged