SASS-3368: Create 'Check Your Answers' page - Interest from gilt-edged or accrued income securities
hmrc/personal-income-tax-submission-frontend pull request #300
Opened 2022-10-18 15:11 UTC by jhkldev

### Description
Create interest from gilt-edged or accrued income securities check your answers page.

[SASS-3368](https://jira.tools.tax.service.gov.uk/browse/SASS-3368)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [X]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [X]  Have you rebased against the current version of main?
- [X]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-10-18 18:43 UTC, satheeshgottemukkula requested changes

2022-10-18 18:43 UTC, satheeshgottemukkula commented on app/views/interest/InterestSecuritiesCYAView.scala.html
> +                        HtmlContent(bigDecimalCurrency(amount.toString)),
Can we move towards right so that total text can be on single line

2022-10-18 18:43 UTC, satheeshgottemukkula commented on app/views/interest/InterestSecuritiesCYAView.scala.html
> +                HtmlContent(messages("interest.securities.cya.questions.1")),
Can we move towards right so that it aligns with rest of the items

2022-10-19 08:35 UTC, jhkldev commented on app/views/interest/InterestSecuritiesCYAView.scala.html
> +                HtmlContent(messages("interest.securities.cya.questions.1")),
The other items exist in an if or map block so the correct indentation is used here.

2022-10-21 11:14 UTC, jhkldev commented on app/views/interest/InterestSecuritiesCYAView.scala.html
> +                        HtmlContent(bigDecimalCurrency(amount.toString)),
The one half CSS class is now specified to prevent the text wrapping in the first column.

2022-10-21 11:14 UTC, jhkldev commented on app/views/interest/InterestSecuritiesCYAView.scala.html
> +                HtmlContent(messages("interest.securities.cya.questions.1")),
The one half CSS class is now specified to prevent the text wrapping in the first column.

2022-10-21 13:10 UTC, satheeshgottemukkula approved these changes

2022-10-21 13:11 UTC, merged