SASS-10571: Add feature switch for EMA + reformat application.conf line spacing
hmrc/personal-income-tax-submission-frontend pull request #391
Opened 2024-12-02 13:27 UTC by BetaDraconis

2024-12-03 10:59 UTC, garytate123 submitted a review, later dismissed

2024-12-03 13:51 UTC, MJCallahanPage requested changes
A few small suggestions

2024-12-03 13:51 UTC, MJCallahanPage commented on app/controllers/predicates/AuthorisedAction.scala
> +      .withDelegatedAuthRule("mtd-it-auth")
I created a `DelegatedAuthRules` object in EnrolmentCommon package so that these constants were centralised with the other `EnrolmentKeys` and `EnrolmentIdentfiers`.

Might be worth doing the same, like:

```
object DelegatedAuthRules {
  val agentDelegatedAuthRule = "mtd-it-auth"
  val supportingAgentDelegatedAuthRule = "mtd-it-auth-supp"
}
```

2024-12-03 13:51 UTC, MJCallahanPage commented on app/controllers/predicates/AuthorisedAction.scala
> +      .withDelegatedAuthRule("mtd-it-auth-supp")
As above

2024-12-03 13:51 UTC, MJCallahanPage commented on conf/application.conf
> +  ema-supporting-agents-enabled = true
Did we not say we would have this `false` by default? Or are we changing that approach now?

2024-12-03 13:51 UTC, MJCallahanPage commented on test/controllers/predicates/AuthorisedActionSpec.scala
> +  trait Test {
This is only used by the Agent tests, so renaming this fixture to `AgentTest` or `AgentFixture` might make it more obvious about where it's used.

2024-12-03 13:51 UTC, MJCallahanPage commented on test/controllers/predicates/AuthorisedActionSpec.scala
> +    val mtdItId: String = "1234567890"
This could move out to the global scope for this spec and be used by the other tests

2024-12-03 13:51 UTC, MJCallahanPage commented on test/controllers/predicates/AuthorisedActionSpec.scala
> +    }
This is only used in one place, which is below. So it might just make sense to call them directly.

2024-12-03 13:51 UTC, MJCallahanPage commented on test/controllers/predicates/AuthorisedActionSpec.scala
> +      setupStubs()
```suggestion
      mockViewAndChangeUrl()
      mockSignInUrl()
```

2024-12-03 15:14 UTC, BetaDraconis commented on conf/application.conf
> +  ema-supporting-agents-enabled = true
I was just using this for testing and forgot to flip it back

2024-12-03 15:17 UTC, BetaDraconis commented on test/controllers/predicates/AuthorisedActionSpec.scala
> +    }
I set this up like this initially on the basis that I might need to override setup stubs but later decided I didn't need to. Will refactor it below as suggested

2024-12-03 15:22 UTC, BetaDraconis commented on test/controllers/predicates/AuthorisedActionSpec.scala
> +    val mtdItId: String = "1234567890"
I was trying to avoid having to make any changes to the other tests. If I pull this mtdItId up into the UnitTest trait it will be easier to make the val global as a lot of these other tests rely on values from that trait which are hardcoded with an MTD ID

2024-12-03 15:54 UTC, MJCallahanPage approved these changes
LGTM 🟢 🚀

2024-12-05 10:52 UTC, garytate123 approved these changes

2024-12-11 09:15 UTC, basotia approved these changes

2024-12-11 09:15 UTC, merged