SASS-10684 Refactor hint on Dividends and update tests
hmrc/personal-income-tax-submission-frontend pull request #392
Opened 2024-12-10 17:14 UTC by garytate123

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2024-12-11 14:27 UTC, joenjones07 submitted a review, later dismissed

2024-12-18 14:14 UTC, MJCallahanPage requested changes
I think this would result in a `fieldset` with a blank `legend` which would be worse. Instead the `legend` should become the page heading

2024-12-18 14:14 UTC, MJCallahanPage commented on app/views/dividends/ReceiveUkDividendsView.scala.html
> -            legendHidden = true,
The `legendHidden` should get set to `false` and the `legendHeading` should still be supplied.

2024-12-18 14:14 UTC, MJCallahanPage commented on app/views/dividends/ReceiveUkDividendsView.scala.html
>      @heading(headingForUse, Some(messages("dividends.caption", (taxYear - 1).toString, taxYear.toString)), "govuk-!-margin-bottom-4")
This should get passed through as the `legendHeading`

2024-12-18 14:14 UTC, MJCallahanPage commented on app/views/dividends/ReceiveUkDividendsView.scala.html
> -            legendHidden = true,
Also the flag `legendAsHeading` should get set to `true`.

2024-12-19 10:27 UTC, MJCallahanPage submitted a review, later dismissed
One small thing, but otherwise LGTM 🟢

2024-12-19 10:27 UTC, MJCallahanPage commented on app/views/dividends/DividendsGatewayView.scala.html
>  @content = {
I know it was already called this, but for readability I think it's worth naming this something like `legendHeading` because it's more meaningful than `content` - just a small refactor whilst we're changing this view.

2024-12-19 10:39 UTC, MJCallahanPage approved these changes
LGTM 🟢

2024-12-19 11:28 UTC, merged