[DM] [SASS-55] Added receive dividends page + a bunch of helpers
hmrc/personal-income-tax-submission-frontend pull request #5
Opened 2020-10-19 14:14 UTC by TheDeadlyPianist

2020-10-19 15:40 UTC, robert-webb-hmrc requested changes
Got a few things to mention, first up would be that we're not hitting our coverage (See image below)
![Screenshot 2020-10-19 at 16 33 05](https://user-images.githubusercontent.com/28566263/96473142-2e057200-1229-11eb-92f3-1372f3ce4140.png)

Secondly, Should this be he UK dividends page or the other Dividends page? I have mentioned this in the review.

Looking at the frontend, it also looks like our gov.uk fonts and styles are not parsing (see image below)
![Screenshot 2020-10-19 at 16 05 36](https://user-images.githubusercontent.com/28566263/96473375-7a50b200-1229-11eb-813d-8f0391e61a6e.png)

R.E. Our error summary, currently clicking on the error summary link does not focus the radios at hand. Also, should we be appending the error key to the url when an error is triggered? (See image below)
![Screenshot 2020-10-19 at 16 26 32](https://user-images.githubusercontent.com/28566263/96473580-bc79f380-1229-11eb-8574-cc163485224f.png)

2020-10-19 15:40 UTC, robert-webb-hmrc commented on app/views/templates/ErrorTemplate.scala.html
> -@(pageTitle: String, heading: String, message: String)(implicit request: Request[_], messages: Messages, appConfig: FrontendAppConfig)
why was frontendAppConfig removed? looking at the income tax submission frontend suggests there is a conflict here.

2020-10-19 15:40 UTC, robert-webb-hmrc commented on test/forms/YesNoFormSpec.scala
> +        val result = yesNoForm.bind(Map(yesNo -> nope)).get
Interesting variation ;)

2020-10-19 15:40 UTC, robert-webb-hmrc commented on conf/messages
> +dividends.receive.heading.agent = Did your client receive any dividends from authorised unit trust, open-ended investment companies or investment trust?
Should these be "Did you receive any dividends from authorised unit trusts, open-ended investment companies or investment trusts?"  and "Did your client receive any dividends from authorised unit trusts, open-ended investment companies or investment trusts?"

2020-10-19 15:40 UTC, robert-webb-hmrc commented on conf/messages
> +dividends.receive.errors.noChoice = Select yes if dividends were received trusts or investment companies
can we double check this with the content guys?

2020-10-19 15:40 UTC, robert-webb-hmrc commented on app/views/templates/helpers/BackLink.scala.html
> +<a href="@url" class="govuk-back-link">Back</a>
Is the intention to make this dynamic, or are we setting them for each page?

2020-10-19 15:40 UTC, robert-webb-hmrc commented on app/views/templates/inputs/YesNoChoice.scala.html
> +    <fieldset class="govuk-fieldset" aria-describedby="changed-name-hint">
Not sure about this aria text

2020-10-19 15:40 UTC, robert-webb-hmrc commented on app/views/templates/inputs/YesNoChoice.scala.html
> +                <label class="govuk-label govuk-radios__label" for="changed-name">
changed-name?

2020-10-19 15:40 UTC, robert-webb-hmrc commented on app/views/templates/inputs/YesNoChoice.scala.html
> +                <label class="govuk-label govuk-radios__label" for="changed-name-2">
changed-name?

2020-10-19 15:40 UTC, robert-webb-hmrc commented on app/views/dividends/ReceiveDividendsView.scala.html
> +    @formWithCsrf(action = controllers.routes.ReceiveDividendsController.submit(), 'novalidate -> "novalidate") {
I'm guessing this will be implemented at a later date?

2020-10-19 15:40 UTC, robert-webb-hmrc commented on app/controllers/ReceiveDividendsController.scala
> +    Ok(receiveDividendsView("dividends.receive.heading." + (if(user.isAgent) "agent" else "client"), YesNoForm.yesNoForm))
The logic looks good here, but would it make more sense to label client "Individual"?

2020-10-20 08:55 UTC, TheDeadlyPianist commented on app/views/templates/ErrorTemplate.scala.html
> -@(pageTitle: String, heading: String, message: String)(implicit request: Request[_], messages: Messages, appConfig: FrontendAppConfig)
We should be importing the Trait class, not the main class itself. Play modules handles the rest for us.

2020-10-20 08:56 UTC, TheDeadlyPianist commented on app/views/templates/inputs/YesNoChoice.scala.html
> +    <fieldset class="govuk-fieldset" aria-describedby="changed-name-hint">
Copied directly from the GovUK elements page

2020-10-20 08:56 UTC, TheDeadlyPianist commented on app/views/templates/inputs/YesNoChoice.scala.html
> +                <label class="govuk-label govuk-radios__label" for="changed-name">
See above. :joy:

2020-10-20 08:57 UTC, TheDeadlyPianist commented on app/views/dividends/ReceiveDividendsView.scala.html
> +    @formWithCsrf(action = controllers.routes.ReceiveDividendsController.submit(), 'novalidate -> "novalidate") {
How do you mean?

2020-10-20 08:57 UTC, TheDeadlyPianist commented on app/controllers/ReceiveDividendsController.scala
> +    Ok(receiveDividendsView("dividends.receive.heading." + (if(user.isAgent) "agent" else "client"), YesNoForm.yesNoForm))
Absolutely correct. Will do.

2020-10-20 10:02 UTC, TheDeadlyPianist commented on app/views/templates/helpers/BackLink.scala.html
> +<a href="@url" class="govuk-back-link">Back</a>
I split it out since it will be on each page, to reduce the amount of replicated code, I just figured it would be better as a helper.

2020-10-20 16:28 UTC, robert-webb-hmrc requested changes
So we're still seeing the gov.uk assets not being loaded in, to fix this we will need to go into the application.scss file and change our assets path to reflect our base url (Please see the equivalent file in the income-tax-submission-frontend)

We are also not getting the error focus upon the clicking of the error link in the summary (Please see image below)
![Screenshot 2020-10-20 at 17 12 18](https://user-images.githubusercontent.com/28566263/96615721-9459c580-12f9-11eb-8732-82e8dec8a06d.png)

All the other changes look fine

2020-10-20 16:28 UTC, robert-webb-hmrc commented on app/controllers/ReceiveDividendsController.scala
> +class ReceiveDividendsController @Inject()(
Would be good if the name of this controller was renamed to reflect the page (Nice to have)

2020-10-21 09:21 UTC, robert-webb-hmrc approved these changes

2020-10-21 09:21 UTC, merged