SASS-198 : Added Change Prior amount page
hmrc/personal-income-tax-submission-frontend pull request #53
Opened 2021-01-18 10:38 UTC by robert-webb-hmrc

Addition of the change prior amount page and other tidy up tasks

2021-01-18 14:51 UTC, matt712 approved these changes

2021-01-18 16:56 UTC, BenCosfordHMRC requested changes

2021-01-18 16:56 UTC, BenCosfordHMRC commented on app/views/templates/helpers/PriorOrNewForm.scala.html
> +                            <span class="govuk-visually-hidden">Error:</span>@messages(error.message)
Could you change "Error:" to use messages

2021-01-18 17:40 UTC, robert-webb-hmrc commented
Updated

2021-01-19 09:17 UTC, BenCosfordHMRC approved these changes

2021-01-19 09:27 UTC, merged