SASS-86 - Added feedback link to the beta bar
hmrc/personal-income-tax-submission-frontend pull request #72
Opened 2021-02-11 09:22 UTC by Dula-J

2021-02-11 09:24 UTC, Dula-J commented on app/config/AppConfig.scala
> +  lazy private val contactFormServiceIdentifier = "uasaitr"
An assumption has been made here in that the serviceIdentifier used as part of the feedbackUrl is "uasaitr" which is an abbreviation of "update and submit an income tax return"

2021-02-11 09:38 UTC, BenCosfordHMRC requested changes

2021-02-11 09:38 UTC, BenCosfordHMRC commented on app/config/AppConfig.scala
> +  lazy private val contactFormServiceIdentifier = "uasaitr"
the identifier can be the full update-and-submit-income-tax-return

2021-02-11 10:11 UTC, Dula-J commented on app/config/AppConfig.scala
> +  lazy private val contactFormServiceIdentifier = "uasaitr"
Updated to "update-and-submit-income-tax-return"

2021-02-12 09:49 UTC, BenCosfordHMRC approved these changes

2021-02-12 09:49 UTC, merged