SASS-276 - Change form type to BigDecimal
hmrc/personal-income-tax-submission-frontend pull request #75
Opened 2021-02-15 16:38 UTC by ina-tu

2021-02-15 17:28 UTC, robert-webb-hmrc requested changes

2021-02-15 17:28 UTC, robert-webb-hmrc commented on app/controllers/dividends/OtherUkDividendsAmountController.scala
> +                    .addingToSession(SessionValues.DIVIDENDS_CYA -> cyaModel.copy(otherUkDividendsAmount = Some(bigDecimal)).asJsonString)
if this form model maps has been changed here, should it also be changed in the app/controllers/dividends/UkDividendsAmountController.scala?

2021-02-15 17:28 UTC, robert-webb-hmrc commented on app/forms/PriorOrNewAmountForm.scala
> -    (isValidCurrency, "common.error.invalid_currency"),
Interestingly, the other currency fields will allow me to input a value with commas like so (99,999,999,999.99) but the prior or new amount fields do not. Would be good to keep these consistent.

![Screenshot 2021-02-15 at 17 26 11](https://user-images.githubusercontent.com/28566263/107977448-0940c180-6fb3-11eb-9c19-0aacfd0bc0ad.png)
![Screenshot 2021-02-15 at 17 26 46](https://user-images.githubusercontent.com/28566263/107977465-0e9e0c00-6fb3-11eb-8c80-afad2ff87fcd.png)

2021-02-16 12:04 UTC, ina-tu commented on app/controllers/dividends/OtherUkDividendsAmountController.scala
> +                    .addingToSession(SessionValues.DIVIDENDS_CYA -> cyaModel.copy(otherUkDividendsAmount = Some(bigDecimal)).asJsonString)
Yes, it should. I'll make those changes

2021-02-16 17:20 UTC, robert-webb-hmrc approved these changes

2021-02-16 17:20 UTC, merged