[DM] [SASS-331] Improved page access restrictions
hmrc/personal-income-tax-submission-frontend pull request #79
Opened 2021-02-18 15:02 UTC by TheDeadlyPianist

2021-02-23 17:15 UTC, robert-webb-hmrc requested changes
Couple of things to check. Can we also rebase this as please?

2021-02-23 17:15 UTC, robert-webb-hmrc commented on app/controllers/dividends/DividendsCYAController.scala
> +      case (None, None, None, None) => Redirect(controllers.dividends.routes.ReceiveUkDividendsController.show(taxYear))
Manually testing this case redirected back to the Overview page, as per the case match on line 82. Will we ever see a cya result with All inputs being none? this is also the case for a true/false response on the UK Dividends page.

2021-02-24 11:03 UTC, TheDeadlyPianist commented on app/controllers/dividends/DividendsCYAController.scala
> +      case (None, None, None, None) => Redirect(controllers.dividends.routes.ReceiveUkDividendsController.show(taxYear))
Deleting line 134 as it cannot happen IRL. Update to create CYA data on journey start, so the user doesn't get thrown to the Overview page if they try and hit the CYA page after pressing Yes.

2021-02-24 11:04 UTC, TheDeadlyPianist commented on app/controllers/interest/InterestCYAController.scala
> +        case (Some(true), None, None, None) => Redirect(controllers.interest.routes.AccountsController.show(taxYear, InterestTaxTypes.UNTAXED))
Update to send user to Amount Controller, not Account Controller.

2021-02-24 11:05 UTC, TheDeadlyPianist commented on app/controllers/interest/InterestCYAController.scala
> +        case _ => Redirect(controllers.interest.routes.AccountsController.show(taxYear, InterestTaxTypes.TAXED))
See above

2021-02-24 17:51 UTC, robert-webb-hmrc approved these changes

2021-02-24 17:51 UTC, merged