[DM] [SASS-407] Updated method for handling confidence level
hmrc/personal-income-tax-submission-frontend pull request #97
Opened 2021-03-09 14:16 UTC by TheDeadlyPianist

2021-03-09 16:17 UTC, matt712 requested changes

2021-03-09 16:17 UTC, matt712 commented on it/controllers/interest/TaxedInterestAmountControllerTest.scala
> +  val taxYear = 2021
Could taxYear be shared in the trait IntegrationTest? I'm only going to comment this once, but it applies across tests.

2021-03-09 16:17 UTC, matt712 commented on test/utils/UnitTest.scala
> +    val agentStuff: Enrolments ~ Some[AffinityGroup] ~ ConfidenceLevel = enrolments and Some(AffinityGroup.Agent) and ConfidenceLevel.L50
agentRetrievals is maybe a better val name than agentStuff

2021-03-10 09:54 UTC, TheDeadlyPianist commented on it/controllers/interest/AccountsControllerTest.scala
Redundant

2021-03-10 10:12 UTC, merged