SASS-353 - Introduced 'Add to list' pattern in the interest account su…
hmrc/personal-income-tax-submission-frontend pull request #99
Opened 2021-03-09 16:18 UTC by Dula-J

…mmary page

2021-03-10 15:35 UTC, robert-webb-hmrc requested changes

2021-03-10 15:35 UTC, robert-webb-hmrc commented on test/views/interest/InterestAccountsViewSpec.scala
> +          InterestAccountModel(Some("azerty"), "Bank of EU", 1234.56) // This is a prior submission
Do we need the comment text here?

2021-03-10 15:56 UTC, Dula-J commented on test/views/interest/InterestAccountsViewSpec.scala
> +          InterestAccountModel(Some("azerty"), "Bank of EU", 1234.56) // This is a prior submission
Will remove it

2021-03-10 16:14 UTC, BenCosfordHMRC commented on app/views/interest/InterestAccountsView.scala.html
> +                <span aria-hidden="true">@messages("common.change")</span>
I think keep the span as aria hidden but include the "change" & "remove" in hidden text

2021-03-10 16:17 UTC, Dula-J commented on app/views/interest/InterestAccountsView.scala.html
> +                <span aria-hidden="true">@messages("common.change")</span>
I don't have a screen reader set up on my machine and no audio output, but i remember @joeyymoore mentioning that adding the verb into the hidden span will result in "Remove Remove Sydney Russell" being read out. Can someone try this out?

2021-03-10 17:29 UTC, robert-webb-hmrc commented on app/views/interest/InterestAccountsView.scala.html
> +                <span aria-hidden="true">@messages("common.change")</span>
That's why I raised this originally, i used voiceover to verify. Anything labelled aria hidden is not read out by the screen reader, which is why we need the verb in the description as well.

2021-03-11 09:49 UTC, Dula-J commented on app/views/interest/InterestAccountsView.scala.html
> +                <span aria-hidden="true">@messages("common.change")</span>
Got you, I'll make the change

2021-03-11 17:26 UTC, robert-webb-hmrc commented on test/views/interest/InterestAccountsViewSpec.scala
> +  private val taxedYesNoForm =
Are these vals the wrong way around?

2021-03-11 17:28 UTC, robert-webb-hmrc requested changes
Just the one test to check. Can we also address these warns as well please?

<img width="1621" alt="Screenshot 2021-03-11 at 16 59 42" src="https://user-images.githubusercontent.com/28566263/110828594-1b024580-828f-11eb-80f7-2325436f9461.png">

<img width="1442" alt="Screenshot 2021-03-11 at 16 58 56" src="https://user-images.githubusercontent.com/28566263/110828621-235a8080-828f-11eb-8b21-44d1bd8a7826.png">

2021-03-12 10:08 UTC, Dula-J commented on test/views/interest/InterestAccountsViewSpec.scala
> +  private val taxedYesNoForm =
yes, good spot

2021-03-12 10:23 UTC, robert-webb-hmrc approved these changes
Changes approved, just waiting on journey tests to be merged

2021-03-12 10:26 UTC, merged